#define COM_HEADER_LEN         4//length of header
#define COM_NULL            0x00//,,
#define COM_ACK             0x01//,,
#define COM_NACK            0x02//,,
#define COM_PING            0x03//,COM_PONG,
#define COM_PONG            0x04//,,
#define COM_TRIGGER         0x05//,COM_ACK,
#define COM_KILL            0x10//,,WIFI
#define COM_RANGING_1       0x11//ranging1,COM_RANGING_2,UWB
#define COM_RANGING_2       0x12//ranging2,COM_RANGING_3,UWB
#define COM_RANGING_3       0x13//ranging3,,UWB
#define COM_REQUEST_MEMORY  0x16//,COM_REPLY_MEMORY,SERIAL
#define COM_REPLY_MEMORY    0x17//,,SERIAL
#define COM_SET_MEMORY      0x18//,COM_ACK,SERIAL
#define COM_REQUEST_DEVICES 0x20//byte,COM_REPLY_DEVICES,
#define COM_REPLY_DEVICES   0x21//deviceList,,
#define COM_REQUEST_STATE   0x22//,COM_REPLY_STATE,
#define COM_REPLY_STATE     0x23//coord,
#define COM_REQUEST_GLOBAL  0x24//globalVarTransfer,COM_REPLY_GLOBAL,
#define COM_REPLY_GLOBAL    0x25//globalVarTransfer,
#define COM_SET_GLOBAL      0x26//globalVarTransfer,COM_ACK,
#define COM_REQUEST_PERIPH  0x27
#define COM_REPLY_PERIPH    0x28
#define COM_SET_PERIPH      0x29
#define COM_REQUEST_ST_EST  0x30//,COM_REPLY_ST_EST,
#define COM_REPLY_ST_EST    0x31//stateEst,,
#define COM_SET_ST_EST      0x32//stateEst,COM_ACK,
#define COM_REQUEST_POS     0x34//globalVarTransfer,COM_REPLY_POS,
#define COM_REPLY_POS       0x35//coord,,
#define COM_SET_POS         0x36//coord,COM_ACK,
#define COM_REQUEST_ATT     0x38
#define COM_REPLY_ATT       0x39
#define COM_SET_ATT         0x3A
#define COM_SET_CTRL_MODE   0x40
#define COM_SET_MOTOR_CMD   0x41//coord,COM_ACK,
#define COM_SET_POS_CMD     0x42//coord,COM_ACK,
#define COM_SET_TRAJ_CMD    0x43
#define COM_REQUEST_WIFI_IP 0x50//,COM_REPLY_WIFI_IP,
#define COM_REPLY_WIFI_IP   0x51//bytes,,
#define COM_REQUEST_FWDMSG  0x52
#define COM_REPLY_FWDMSG    0x53

#define NULL_MODE           0x00
#define MOTOR_SETPOINT_MODE 0x01
#define POS_SETPOINT_MODE   0x02
#define TRAJECTORY_MODE     0x03
#define FLIGHT_MODE_BOUNDS  0x03